


import { Inter } from 'next/font/google'

import { Toaster } from 'react-hot-toast'
import MainLayout from '@/components/MainLayout'
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Nexus classic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
  
  return (
    <>
      <MainLayout>{children}</MainLayout>

      <Toaster />
    </>
  );
}
