
import ReduxProvider from '@/redux/ReduxProvider'
import './globals.css'


import { Toaster } from 'react-hot-toast'



export const metadata = {
  title: 'Nexus classic',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
  }) {
  
  
  return (
    <html lang="en">
      <body >
        <ReduxProvider>
       

        {children}
          
   </ReduxProvider>

    
        <Toaster />
      </body>
    </html>
  );
}
