import { Plan } from "@prisma/client";

export const advertOptions = [
  { value: "", label: "--select--" },
  { value: "for sale", label: "for sale" },
  { value: "for rent", label: "for rent" },

];

export const propertyType = [
  { value: "", label: "--select--" },
  { value: "Duplex", label: "Duplex" },
  { value: "Flat Apartment", label: "Flat Apartment" },
  { value: "Terrace", label: "Terrace" },
  { value: "Detached", label: "Detached" },
  { value: "Bungalow", label: "Bungalow" },
  { value: "Studio", label: "Studio" },
  { value: "Semi Detached", label: "Semi Detached" },
  { value: "Mansion", label: "Mansion" },
  { value: "Town House", label: "Town House" },
  { value: "Office Space", label: "Office Space" },
  { value: "Shop", label: "Shop" },
  { value: "Warehouse", label: "Warehouse" },
  { value: "Penthouse", label: "Penthouse" },
  { value: "Land", label: "Land" },
  { value: "Maisonettes", label: "Maisonettes" },
  { value: "High Rise", label: "High Rise" },
  { value: "Block of Flats", label: "Block of Flats" },
  { value: "Hotel", label: "Hotel" },
  { value: "Factory", label: "Factory" },
  { value: "Commercial Property", label: "Commercial Property" },
  { value: "Workspace", label: "Workspace" },
  { value: "Mini Flat", label: "Mini Flat" },
  { value: "House", label: "House", selected: true },
];

export const propertyUse = [
  { value: "", label: "--select--" },
  { value: "Residential", label: "Residential" },
  { value: "Commercial", label: "Commercial" },
  {
    value: "Either Residential or Commercial",
    label: "Either Residential or Commercial",
  },
  { value: "Educational", label: "Educational" },
  { value: "Religious", label: "Religious" },
  { value: "Unspecified", label: "Unspecified", selected: true },
  { value: "Shortlet", label: "Shortlet" },
];

export const available = [
  { value: "", label: "--select--" },
  { value: "Available", label: "Available" },
  { value: "Now Selling", label: "Now Selling" },
  { value: "Coming Soon", label: "Coming Soon" },
  { value: "Unavailable", label: "Unavailable" },
  { value: "Sold Out", label: "Sold Out" },
  { value: "SOLD", label: "SOLD" },
  { value: "Rented / Leased", label: "Rented / Leased" },
];

export const currency = [
  { value: "₦ - Nigeria Naira", label: "₦ - Nigeria Naira" },
  { value: "$ - US Dollar", label: "$ - US Dollar" },
  { value: "₤ - British Pound", label: "$ - US Dollar" },
];
export const totalArea = [
  { value: "sqm", label: "sqm" },
  { value: "heactares", label: "heactares" },
  { value: "acres", label: "acres" },
  { value: "plots", label: "plots" },
  { value: "sqft", label: "sqft" },
];

export const plans_details = [
  // {
    
  //   value: "No of Listings Per Month",
  //   label: "Number of Listings Per Month",
  // },
  // {
    
  //   value: "Listing Expiry",
  //   label: "Listing Expiry",
  // },
  // {
    
  //   value: "Refresh Listings",
  //   label: "Refresh Listings",
  // },
  // {
    
  //   value: "No of Photo Upload",
  //   label: "Number of Photo Upload",
  // },
  // {
    
  //   value: "No of Featured Listings",
  //   label: "Number of Featured Listings",
  // },
  // {
    
  //   value: "No of Listing Boosts",
  //   label: "Number of Listing Boosts",
  // },
  {
    
    value: "Document Upload",
    label: "Document Upload",
  },
  {
    
    value: "Branded Ads/Listings",
    label: "Branded Ads/Listings",
  },
  {
    
    value: "Video Upload",
    label: "Video Upload",
  },
  {
    
    value: "Virtual Tour Embed",
    label: "Virtual Tour Embed",
  },
  {
    
    value: "View Property Requests",
    label: "View Property Requests",
  },
  {
    
    value: "Dedicated Customer Support",
    label: "Dedicated Customer Support",
  },
  {
    
    value: "Social Media Promotion",
    label: "Social Media Promotion",
  },
  {
    
    value: "Featured in Directory",
    label: "Featured in Directory",
  },
  {
    
    value: "Advert-Free Website",
    label: "Advert-Free Website",
  },
  {
    
    value: "Profile Featured in Search Result",
    label: "Profile Featured in Search Result",
  },
  {
    
    value: "Email Marketing",
    label: "Email Marketing",
  },
];


export const limited_stock = [
  {
    img: "../houserent1.jpg",
    description: "1 bedroom house shortlet",
    price: 45500000,
    discount: 50000000,
  },
  {
    img: "../houserent5.jpg",
    description: "4 bedroom detached for rent",
    price: 7000000,
    discount: 8000000,
  },
  {
    img: "../houserent3.jpg",
    description: "4 bedroom flat apt for rent",
    price: 75000000,
    discount: 80000000,
  },
  {
    img: "../houserent6.jpg",
    description: "4 bedroom flat apt for rent",
    price: 4000000,
    discount: 5000000,
  },
  {
    img: "../houserent7.jpg",
    description: "1 bedroom house shortlet",
    price: 4500000,
    discount: 5000000,
  },
  {
    img: "../houserent9.jpg",
    description: "4 bedroom flat apt for sale",
    price: 75000000,
    discount: 80000000,
  },
  {
    img: "../houserent10.jpg",
    description: "4 bedroom flat apt for rent",
    price: 4000000,
    discount: 5000000,
  },
  {
    img: "../houserent11.jpg",
    description: "1 bedroom house shortlet",
    price: 45500000,
    discount: 50000000,
  },
];


export const top_selling = [
  {
    img: "../houserent3.jpg",
    description: "5 bedroom Terrace for sale",
    price: 150000000,
    discount: 160000000,
  },
  {
    img: "../housetop9.jpg",
    description: "4 bedroom Terrace for sale",
    price: 65000000,
    discount: 70000000,
  },
  {
    img: "../housetop10.jpg",
    description: "3 bedroom flat Apartment",
    price: 55000000,
    discount: 60000000,
  },
  {
    img: "../housetop7.jpg",
    description: "4 bedroom Duplex for sale",
    price: 45000000,
    discount: 50000000,
  },
  // {
  //   img: "../housetop5.jpg",
  //   description: "5 bedroom Terrace for sale",
  //   price: 800000000,
  //   discount: 160000000,
  // },
  // {
  //   img: "../housetop6.jpg",
  //   description: "8 bedroom Terrace for sale",
  //   price: 7000000000,
  //   discount: 5000000,
  // },
  // {
  //   img: "../housetop9.jpg",
  //   description: "6 bedroom Terrace for sale",
  //   price: 650000000,
  //   discount: 5000000,
  // },
  // {
  //   img: "../housetop2.jpg",
  //   description: "6 bedroom Terrace for sale",
  //   price: 350000000,
  //   discount: 5000000,
  // },
];


export const priceOptions = [
  { value: "0", label: "Max Price" },
  { value: "500000", label: "₦500,000" },
  { value: "1000000", label: "₦1,000,000" },
  { value: "1500000", label: "₦1,500,000" },
  { value: "2000000", label: "₦2,000,000" },
  { value: "2500000", label: "₦2,500,000" },
  { value: "3000000", label: "₦3,000,000" },
  { value: "3500000", label: "₦3,500,000" },
  { value: "4000000", label: "₦4,000,000" },
  { value: "4500000", label: "₦4,500,000" },
  { value: "5000000", label: "₦5,000,000" },
  { value: "5500000", label: "₦5,500,000" },
  { value: "6000000", label: "₦6,000,000" },
  { value: "6500000", label: "₦6,500,000" },
  { value: "7000000", label: "₦7,000,000" },
  { value: "7500000", label: "₦7,500,000" },
  { value: "8000000", label: "₦8,000,000" },
  { value: "8500000", label: "₦8,500,000" },
  { value: "9000000", label: "₦9,000,000" },
  { value: "9500000", label: "₦9,500,000" },
  { value: "10000000", label: "₦10,000,000" },
  { value: "10500000", label: "₦10,500,000" },
  { value: "11000000", label: "₦11,000,000" },
  { value: "11500000", label: "₦11,500,000" },
  { value: "12000000", label: "₦12,000,000" },
  { value: "12500000", label: "₦12,500,000" },
  { value: "13000000", label: "₦13,000,000" },
  { value: "13500000", label: "₦13,500,000" },
  { value: "14000000", label: "₦14,000,000" },
  { value: "14500000", label: "₦14,500,000" },
  { value: "15000000", label: "₦15,000,000" },
  { value: "15500000", label: "₦15,500,000" },
  { value: "16000000", label: "₦16,000,000" },
  { value: "16500000", label: "₦16,500,000" },
  { value: "17000000", label: "₦17,000,000" },
  { value: "17500000", label: "₦17,500,000" },
  { value: "18000000", label: "₦18,000,000" },
  { value: "18500000", label: "₦18,500,000" },
  { value: "19000000", label: "₦19,000,000" },
  { value: "19500000", label: "₦19,500,000" },
  { value: "20000000", label: "₦20,000,000" },
  { value: "20500000", label: "₦20,500,000" },
  { value: "21000000", label: "₦21,000,000" },
  { value: "21500000", label: "₦21,500,000" },
  { value: "22000000", label: "₦22,000,000" },
  { value: "22500000", label: "₦22,500,000" },
  { value: "23000000", label: "₦23,000,000" },
  { value: "23500000", label: "₦23,500,000" },
  { value: "24000000", label: "₦24,000,000" },
  { value: "24500000", label: "₦24,500,000" },
  { value: "25000000", label: "₦25,000,000" },
  { value: "25500000", label: "₦25,500,000" },
  { value: "26000000", label: "₦26,000,000" },
  { value: "26500000", label: "₦26,500,000" },
  { value: "27000000", label: "₦27,000,000" },
  { value: "27500000", label: "₦27,500,000" },
  { value: "28000000", label: "₦28,000,000" },
  { value: "28500000", label: "₦28,500,000" },
  { value: "29000000", label: "₦29,000,000" },
  { value: "29500000", label: "₦29,500,000" },
  { value: "30000000", label: "₦30,000,000" },
  { value: "30500000", label: "₦30,500,000" },
  { value: "31000000", label: "₦31,000,000" },
  { value: "31500000", label: "₦31,500,000" },
  { value: "32000000", label: "₦32,000,000" },
  { value: "32500000", label: "₦32,500,000" },
  { value: "33000000", label: "₦33,000,000" },
  { value: "33500000", label: "₦33,500,000" },
  { value: "34000000", label: "₦34,000,000" },
  { value: "34500000", label: "₦34,500,000" },
  { value: "35000000", label: "₦35,000,000" },
  { value: "35500000", label: "₦35,500,000" },
  { value: "36000000", label: "₦36,000,000" },
  { value: "36500000", label: "₦36,500,000" },
  { value: "37000000", label: "₦37,000,000" },
  { value: "37500000", label: "₦37,500,000" },
  { value: "38000000", label: "₦38,000,000" },
  { value: "38500000", label: "₦38,500,000" },
  { value: "39000000", label: "₦39,000,000" },
  { value: "39500000", label: "₦39,500,000" },
  { value: "40000000", label: "₦40,000,000" },
  { value: "40500000", label: "₦40,500,000" },
  { value: "41000000", label: "₦41,000,000" },
  { value: "41500000", label: "₦41,500,000" },
  { value: "42000000", label: "₦42,000,000" },
  { value: "42500000", label: "₦42,500,000" },
  { value: "43000000", label: "₦43,000,000" },
  { value: "43500000", label: "₦43,500,000" },
  { value: "44000000", label: "₦44,000,000" },
  { value: "44500000", label: "₦44,500,000" },
  { value: "45000000", label: "₦45,000,000" },
  { value: "45500000", label: "₦45,500,000" },
  { value: "46000000", label: "₦46,000,000" },
  { value: "46500000", label: "₦46,500,000" },
  { value: "47000000", label: "₦47,000,000" },
  { value: "47500000", label: "₦47,500,000" },
  { value: "48000000", label: "₦48,000,000" },
  { value: "48500000", label: "₦48,500,000" },
  { value: "49000000", label: "₦49,000,000" },
  { value: "49500000", label: "₦49,500,000" },
  { value: "50000000", label: "₦50,000,000" },
];



// default plan

export const freeplan:Omit<Plan, 'id'|'createdAt' |'updatedAt' > = {
  title: "Free Plan",
  max_listings: 5,
video_uploads:'',
  image_uploads: '4',
  price: 0,
  other_features:'[]'
}

export const basicplan: Omit<Plan, "id" | "createdAt" | "updatedAt"> = {
  title: "Basic Plan",
  max_listings: 10,
  video_uploads: "", 
  image_uploads: "7",
  price: 10000,
  other_features: "[]",
};

export const goldplan: Omit<Plan, "id" | "createdAt" | "updatedAt"> = {
  title: "Gold Plan",
  max_listings: 20,
  video_uploads: "1",
  image_uploads: "10",
  price: 25000,
  other_features: "[]",
};
export const platinumplan: Omit<Plan, "id" | "createdAt" | "updatedAt"> = {
  title: "Platinum Plan",
  max_listings: 1000,
  video_uploads: "unlimited",
  image_uploads: "unlimited",
  price: 50000,
  other_features: "[]",
};


export const cities = {
  Lagos: [
    "Aba",
    "Aba-Onigbagbo",
    "Aba-Oriyanrin",
    "Abaranje",
    "Abegede",
    "Abijo",
    "Abiya",
    "Abomiti",
    "Abosan",
    "Abosioto",
    "Abule Ado",
    "Abule Ijesha",
    "Abule Oshun",
    "Abule-Egba",
    "Abule-Nla",
    "Abule-Okuta",
    "Adekunle",
    "Adeleye",
    "Ado",
    "Agadangba",
    "Agaja",
    "Agala",
    "Agani",
    "Agbede",
    "Agbelekale",
    "Agbo-Fipe",
    "Agbogbe",
    "Agboju",
    "Agbole",
    "Agbowa",
    "Age-Mowo",
    "Agege",
    "Agidi",
    "Agidingbi",
    "Ago-Hausa",
    "Ago-Tuntun",
    "Agodo",
    "Agomu",
    "Aguda",
    "Agun",
    "Agunfoye",
    "Agunmo",
    "Agura",
    "Ahanfe",
    "Aiyeteju",
    "Aiyetoro",
    "Aiyetoto-Asogun",
    "Ajah",
    "Ajara-Agarrabe",
    "Ajara-Doko",
    "Ajara-Iveda",
    "Ajara-Topa",
    "Ajebo",
    "Ajegbenwa",
    "Ajegunle",
    "Ajibade",
    "Ajido",
    "Ajido-Elikiti",
    "Akangba",
    "Akara Kumo",
    "Akere",
    "Akesan",
    "Akinde",
    "Akinogun",
    "Akinyele",
    "Akitan",
    "Akodo",
    "Akoka",
    "Akoko",
    "Akowonjo",
    "Alaba",
    "Alagba",
    "Alagbado",
    "Alagbede",
    "Alaguntan",
    "Alaka",
    "Alakuko",
    "Alapadi",
    "Alapako",
    "Alasia",
    "Alausa",
    "Ale",
    "Aliayabiagba",
    "Alimosho",
    "Amukoko",
    "Amuwo",
    "Angorin",
    "Animshaun",
    "Anthony",
    "Apa",
    "Apala",
    "Apapa",
    "Apapa Eleko",
    "Apese",
    "Aradogun",
    "Arapagi",
    "Araromi",
    "Araromi-Tope",
    "Arida",
    "Asepe - Musin",
    "Asipa",
    "Atan",
    "Awoyaya",
    "Ayobo",
    "Badagry",
    "Badore",
    "Bagbagbelu",
    "Baiyeku",
    "Balogun",
    "Bamgbose",
    "Bariga",
    "Baruwa",
    "Bolorunpelu",
    "Cardoso",
    "Coker",
    "Command",
    "Dankaka",
    "Doforo-Ganyingbo",
    "Dongo",
    "Dopemu",
    "Ebute Ikorodu",
    "Ebute-Lekki",
    "Ebute-Metta",
    "Efiran",
    "Egan",
    "Egba",
    "Egbe",
    "Egbeda",
    "Egun",
    "Ejigbo",
    "Ejirin",
    "Ekoro",
    "Eleputu",
    "Elesin",
    "Elikiti",
    "Eluju",
    "Emina",
    "Emuren",
    "Epe",
    "Era",
    "Ere-Ise",
    "Eredo",
    "Erunkan",
    "Erutan",
    "Etegbin",
    "Eti-Osa",
    "Ewu",
    "Ewu Ebi",
    "Fadeyi",
    "Fagba",
    "Falana",
    "Falomo",
    "Farasime",
    "Fatade",
    "Fawosedi",
    "Festac Town",
    "FHA Estate",
    "Folu",
    "Fongi-Odo",
    "Gafa",
    "Ganmer",
    "Ganyingbo",
    "Gbagada",
    "Gbagidan",
    "Gbaj",
    "Gbanko",
    "Gberegbe",
    "Gbodo",
    "Gbogbo",
    "Gbogije",
    "Gbogije-Ibeju",
    "Gbokuta",
    "Gedu",
    "George",
    "Ginti",
    "Henume",
    "Iba",
    "Ibasa",
    "Ibeju",
    "Ibere",
    "Ibereko",
    "Iberekodo",
    "Ibese",
    "Ibiku",
    "Ibode",
    "Iboju",
    "Ibon",
    "Ibonwon",
    "Idanwu",
    "Idaso",
    "Iddo",
    "Ide",
    "Ideno",
    "Idi Araba",
    "Idimu",
    "Idiori",
    "Idioro",
    "Idobase",
    "Idoluwo",
    "Idomu",
    "Idowu",
    "Ifako",
    "Ifako-Agege",
    "Igando",
    "Iganmu",
    "Igbaga",
    "Igbalu",
    "Igbe Ewoliwo",
    "Igbede",
    "Igbein",
    "Igbin",
    "Igbo",
    "Igbo Ejo",
    "Igbo Elerin",
    "Igbo Iroko",
    "Igbo-Apawa",
    "Igbo-Lomi",
    "Igbo-Olorun",
    "Igbobi",
    "Igbodu",
    "Igboefon",
    "Igbogbele",
    "Igbogila",
    "Igbogun",
    "Igbokin",
    "Igbolobi",
    "Igbologun",
    "Igbopa",
    "Igbore",
    "Igborosun",
    "Igboshere",
    "Igoro",
    "Ijaiye",
    "Ijanikin",
    "Ijavie",
    "Ijede",
    "Ijedodo",
    "Ijegemo",
    "Ijegun",
    "Ijero",
    "Ijesha-Tedo",
    "Ijora",
    "Ijora Village",
    "Ijotan",
    "Iju",
    "Iju Junction",
    "Ikare",
    "Ikate",
    "Ikeja",
    "Ikeja Government Reserved Area",
    "Ikeran",
    "Ikola",
    "Ikorodu",
    "Ikosi",
    "Ikosi-Ketu",
    "Ikotun",
    "Ikoyi",
    "Ikuata",
    "Ilado",
    "Ilado Ogunu",
    "Ilagbo",
    "Ilaje Camp",
    "Ilaje Fishing Camp",
    "Ilapo",
    "Ilasa",
    "Ilasamaja",
    "Ilege",
    "Ilemere",
    "Ilogbo",
    "Ilogbo Elegba",
    "Ilumofin",
    "Ilupeju",
    "Imare",
    "Imeke",
    "Imeseju",
    "Imoba",
    "Imope",
    "Imore",
    "Imoru",
    "Imota",
    "Imuofo",
    "Imuogo",
    "Inogbe",
    "Inoka",
    "Inupa",
    "Ipaja",
    "Ipakan",
    "Ipanmi",
    "Ipara",
    "Ipesu",
    "Ipewu",
    "Iponri",
    "Ipota",
    "Ira",
    "Iragbo",
    "Iragon",
    "Iranla",
    "Irede",
    "Irewe",
    "Irosu",
    "Iru",
    "Isaga-Tedo",
    "Isagira",
    "Isalu",
    "Isasi",
    "Isawo",
    "Ise",
    "Iseri-Oshun",
    "Isheri Olofin",
    "Isheri-Olofin",
    "Isiwu",
    "Isolo",
    "Ison",
    "Isunba",
    "Ita",
    "Itamoga",
    "Itire",
    "Itirin",
    "Ito-Omu",
    "Itoga",
    "Itohun",
    "Itokin",
    "Iwaya",
    "Iwaye",
    "Iwerekun",
    "Iwesolu",
    "Iworo",
    "Iyafin",
    "Iyagbe",
    "Jaguna",
    "Janoke",
    "Jibowu",
    "Kadara",
    "Kajola",
    "Kakon",
    "Kese",
    "Ketu",
    "Kirikiri",
    "Kweme",
    "Ladeba",
    "Ladega",
    "Ladekin",
    "Ladugbo",
    "Lagos",
    "Lagos Island",
    "Lakowe",
    "Lamija",
    "Langbasa",
    "Lasu",
    "Lawani Oguntayo",
    "Lekki",
    "Lekki Peninsula",
    "Lemba",
    "Losi",
    "Mafoluku",
    "Magbon",
    "Magodo I",
    "Magodo II",
    "Magun",
    "Maiyegun",
    "Majidun Ilaje",
    "Makoko",
    "Malekete",
    "Maroko",
    "Maryland",
    "Matogunde",
    "Maya",
    "Mebamu",
    "Meiran",
    "Meki",
    "Mekunwen",
    "Mende",
    "Mile Twelve",
    "Moba",
    "Mobido",
    "Mojoda",
    "Mopo Onijebu",
    "Mopo-Akinlade",
    "Mosafejo",
    "Mosan",
    "Mosere Ikoga",
    "Mowo",
    "Moyopa",
    "Mushin",
    "Naforija",
    "New Lagos",
    "Oba-Oyinbo",
    "Obada",
    "Obadore",
    "Obalende",
    "Obanikoro",
    "Obele",
    "Odo",
    "Odo Ragun",
    "Odo-Ayandelu",
    "Odo-Mola",
    "Odogun",
    "Oduwole",
    "Ofin",
    "Ogba",
    "Ogogoro",
    "Ogombo",
    "Ogoyo",
    "Ogudu",
    "Ogungbe",
    "Oguntedo",
    "Ojagemo",
    "Ojo",
    "Ojodu",
    "Ojogun",
    "Ojota",
    "Ojuolokun",
    "Oke Afa",
    "Oke Agba",
    "Oke Eletu",
    "Oke Ogbe",
    "Oke Oloku",
    "Oke-Ira",
    "Oke-Lisa",
    "Oke-Odo",
    "Oko Ito",
    "Oko Orisa",
    "Oko-Abe",
    "Oko-Eko",
    "Okokomaiko",
    "Okun-Ibese",
    "Okunaja",
    "Okunegun",
    "Okunola",
    "Okunsolu",
    "Olasore",
    "Olodi-Apapa",
    "Ologode",
    "Ologogoro",
    "Olorunda",
    "Olowora",
    "Olusosun",
    "Oluti",
    "Oluwa",
    "Omole",
    "Omu",
    "Ondotedo",
    "Onigangan",
    "Onigbokun",
    "Onigbongbo",
    "Onijawajawa",
    "Onike",
    "Onipanu",
    "Onitiri",
    "Opamore",
    "Opebi",
    "Oregun",
    "Orepete",
    "Oreta",
    "Ori-Ita",
    "Oriba",
    "Origele",
    "Orile",
    "Orile Oshodi",
    "Orile-Iganmu",
    "Orimedu",
    "Orishigun",
    "Orita-Bodun",
    "Oroke",
    "Oruba",
    "Orugba",
    "Osho",
    "Oshodi",
    "Ososun",
    "Oto",
    "Otolu",
    "Otta",
    "Otto",
    "Owode-Ise",
    "Oworonsoki",
    "Oyewo",
    "Oyingbo",
    "Panko",
    "Papa Ajao",
    "Papa-Ashafa",
    "Parafa",
    "Pasi",
    "Pedro",
    "Poka",
    "Povita",
    "Ropoji",
    "Sabi",
    "Saga",
    "Salabo",
    "Sangotedo",
    "Satellite Town",
    "Seidu",
    "Seje I",
    "Seje II",
    "Sekungba",
    "Shala",
    "Shangisha",
    "Shiwoku",
    "Shogunle",
    "Siriwon",
    "Somolu",
    "Subero Oje",
    "Suberu Oje",
    "Surulere",
    "Tafi",
    "Take",
    "Tamaro",
    "Tarkwa Bay",
    "Tatala",
    "Tedi Muwo",
    "Tewon",
    "Tinubu",
    "Tiye",
    "Tofa",
    "Topo",
    "Trade Fair",
    "Victoria Island Annex",
    "Volkswagen",
    "Wasimi Ojokoro",
    "Wasimi-Aiyetoro",
    "Weke",
    "Wesere",
    "Yaba",
    "Yegunda",
    "Zinvie",
  ],
  Abuja: [
    "Abaji",
    "Abuja",
    "Adadu",
    "Agbe",
    "Agena",
    "Aji",
    "Akori",
    "Alita",
    "Anagada",
    "Anagbaki",
    "Anguwan-Lafia",
    "AnguwanBako",
    "Anka",
    "Ankuru",
    "Ashera",
    "Aso",
    "Asokoro",
    "Atako",
    "Awa",
    "Baban-Kurmi",
    "Baban-Rafi",
    "Bako",
    "Bangwo",
    "Barari",
    "Barnashi",
    "Barwa",
    "Bassa",
    "Bogu",
    "Boi",
    "Bokwoi",
    "Budupe",
    "Bugako",
    "Buko",
    "Burum",
    "Buze",
    "Bwari",
    "Bwom",
    "Cheta",
    "Chigwai",
    "Cida",
    "Cukumi",
    "Dadabiri",
    "Dadaje",
    "Daduma",
    "Dafa",
    "Dafara",
    "Dafare",
    "Dakaa",
    "Dakibiu",
    "Dako",
    "Dakwa",
    "Dangara",
    "Dapa",
    "Dawari",
    "Dawliko",
    "Dereguma",
    "Dewu",
    "Digbe",
    "Dikwa",
    "Dirimi-Sabo",
    "Dobi",
    "Dubeidna",
    "Duda",
    "Duma",
    "Durumi",
    "Dushekoro",
    "Dushepe",
    "Dutsekpa",
    "Ebhor",
    "Ebwa",
    "Eka",
    "Ekpa",
    "Foibi",
    "Foroko",
    "Fuka",
    "Fukafu",
    "Furah",
    "Fwoge",
    "Gaba",
    "Gada",
    "Gadara",
    "Gago",
    "Gaida",
    "Gajabe",
    "Galadimawa",
    "Gam",
    "Gana",
    "Gapare",
    "Garki",
    "Garu",
    "Garui",
    "Gasakba",
    "Gashe",
    "Gatere",
    "Gaube",
    "Gawu",
    "Gawu Dabara",
    "Gazarago",
    "Gbanbo",
    "Gbogbodo",
    "Gboro",
    "Gbuduyi",
    "Gerki",
    "Ghakasu",
    "Ghamgwa",
    "Gidan Gogo",
    "Gidan Maiaki",
    "Gidan Nbora",
    "Gidan Pawa",
    "Gidan Shaba",
    "Gidan-Bahagwo",
    "Gidan-Bijimi",
    "Gidan-Choko",
    "Gidan-Dutse",
    "Gidan-Gwari",
    "GidanAudu",
    "GidanBawa",
    "Gidanbi",
    "GidanJatau",
    "Gidansa",
    "Ginda",
    "GiwauKurmi",
    "Gnuto",
    "Gobe",
    "Gomani",
    "Gora",
    "Guako",
    "Gudaba",
    "Gude",
    "Guduga",
    "Gunagu",
    "Gunrafia",
    "Gunufufu",
    "Guredi",
    "Gurfata",
    "Gurushe",
    "Gwagwa",
    "Gwagwa Rafi",
    "Gwagwalada",
    "Gwako",
    "Gwal",
    "Gwargwada",
    "Gwari",
    "Gwari-Yamma",
    "Gwarinpa",
    "Gwau",
    "Gwaupe",
    "Gwi",
    "Gwoi",
    "Gwoi-Obere",
    "Gwombe",
    "Ibabban Tsuani",
    "Idogwari",
    "IdonBasa",
    "Idu",
    "Igu",
    "Ija Gwari",
    "Ike",
    "Isuanin Kura",
    "Jabi",
    "Jadabuta",
    "Jahi",
    "Jaita",
    "Jakoro",
    "Jarana",
    "Jidu",
    "Jigape",
    "Jikakuchi",
    "Jikoko",
    "Jimpe",
    "Jiru",
    "Jugbedo",
    "Jugodo",
    "Juwa",
    "Kaba",
    "Kabi",
    "Kabusa",
    "Kabusu Koro",
    "Kado",
    "Kadobunkuro",
    "Kafa",
    "Kafat",
    "Kagini",
    "Kaida",
    "Kamadi",
    "Kanzo",
    "Karako",
    "Karmu",
    "Karonmajigi",
    "Karsana",
    "Karshi",
    "Karu",
    "Karum",
    "Kasada",
    "Kashimoro",
    "Katambe",
    "Kato",
    "Kau",
    "Kaudisi",
    "Kauye",
    "Ketti",
    "Kigbe",
    "Koda",
    "Kofuwa",
    "Kogi",
    "Koroko",
    "Kpako",
    "Kpeyi",
    "Kpoto",
    "Kubabo",
    "Kubmana",
    "Kubwa Suburban District",
    "Kuchbuni",
    "Kudiri",
    "Kugo",
    "Kuje",
    "Kujekpa",
    "Kuji",
    "Kukwaba",
    "Kumao",
    "Kundu",
    "Kunk",
    "Kurmin-Daudu",
    "Kuro",
    "Kurudu",
    "Kurunduma",
    "Kusafe",
    "Kusaki",
    "Kushi",
    "Kutada",
    "Kutiva",
    "Kutunbui",
    "Kwaita",
    "Kwakoto",
    "Kwakwa",
    "Kwali",
    "Kwalita",
    "Kwarana",
    "Kwashimbi",
    "Kwaye",
    "Kwonkashe",
    "Kwutara",
    "Kyawu",
    "Lafia Mbaka",
    "Leda",
    "Ledi",
    "Lele-Ye-Saba-Basa",
    "Lugbe Suburban District",
    "Madala",

    "Madna",
    "Maitama",
    "Maje",
    "Mamusa",
    "Manderegi",
    "Mape",
    "Marke",
    "Mashapa",
    "Mobushipe",
    "Mono",
    "Mpape",
    "Mudu",
    "Mule",
    "Munafe",
    "Nago",
    "Nagpakuku",
    "Nanda",
    "Ndeshi",
    "Nitse",
    "Nuku",
    "Nukuchi",
    "Numa",
    "Nyanya Suburban District",
    "Nyimbo",
    "Orozo",
    "Padan-Gwari",
    "Pai",
    "Paiko",
    "Paipe",
    "Pandaji",
    "Panpanpi",
    "Paputache",
    "Parfun",
    "Pasali",
    "Pasere",
    "Pashi",
    "Pate",
    "Pege",
    "Pewi",
    "Pigwa",
    "Pima",
    "Piowe",
    "Piri",
    "Pmadna",
    "Pozema",
    "Punyi",
    "Pyakasa",
    "Pyakasa-Mabi",
    "Rafin Pa",
    "Reda",
    "Rije",
    "Rubatu",
    "Rubochi",
    "Rubuchi",
    "Runji",
    "Ruwaza",
    "SabanPlyore",
    "Sabe",
    "Sabo",
    "Sabo Kukwaba",
    "Sabojibi",
    "Sabokarumo",
    "Sabon Gari",
    "Sabon Gida",
    "Sabon-Gida",
    "Sagiya",
    "Sagwari",
    "Salaji",
    "Salirulu",
    "Sankache",
    "Sape",
    "Saupe",
    "Shara",
    "Shebona",
    "Sheda",
    "Shenagu",
    "Sherat",
    "Shere",
    "Shereti",
    "Shesoko",
    "Shishipe",
    "Simami",
    "Sota",
    "Sukuku",
    "Tabe",
    "Tagwar",
    "Taka-Lafia",
    "Takunda",
    "Takura",
    "Takushira",
    "TakushiraHausa",
    "Takworiki",
    "Tampe",
    "Tando",
    "Tasha",
    "Tashepape",
    "Tasunnkufa",
    "Tika",
    "Tudar",
    "Tude",
    "Tudun Wada",
    "Tuea",
    "Tukuba",
    "Tukuro",
    "Tunga",
    "Tunga Maje",
    "Tunga-Bawa",
    "Tungan Ali",
    "Tungan Daudu",
    "Tungan Galadima",
    "Tungan Kaki",
    "Tungan Pa",
    "Tungan Sarki",
    "Tungan Tofa",
    "Tungan Wada",
    "TunganFulani",
    "Tungun-Adufa",
    "Ushapa",
    "Waje",
    "Waru",
    "Wasa",
    "Wawa",
    "Wosika",
    "Wumba",
    "Wuna",
    "Wunale",
    "Wupa",
    "Wuse",
    "Yaba",
    "Yabo",
    "Yambabu",
    "Yance",
    "Yanga",
    "Yangoji",
    "Yanyan",
    "Yarwa",
    "Yebu",
    "Yehidna",
    "Yelua",
    "Yelwa",
    "Yeuye",
    "Yewu",
    "Yewuni",
    "Zagabutu",
    "Zango-Kara",
    "ZangonKara",
    "Zawa",
    "Zege",
    "Zida",
    "Ziona",
    "Zongo",
    "Zuba",
    "Zui",
  ],
  Rivers: [
    "Abalama",
    "Abonnema",
    "Afam",
    "Ahoada",
    "Andoni",
    "Ataba",
    "Bane",
    "Bonny",
    "Bori",
    "Billie",
    "Bodo",
    "Buguma",
    "Degema Town",
    "Eberi",
    "Elele",
    "Emohua",
    "Igrita",
    "Igwuruta",
    "Igbo-Etche",
    "Kula",
    "Mbiama",
    "Nkoro",
    "Odiabidi",
    "Okehi",
    "Okobie",
    "Okoloma",
    "Okomoko",
    "Okrika",
    "Omoku",
    "Onne",
    "Opobo",
    "Oyorokoto",
    "Oyigbo",
    "Port Harcourt (capital and largest city)",
    "Rumuokoro",
    "Umuagbai",
    "Umuru",
    "Usokun-Degema",
    "Unyeada Kingdom",
  ],
  Enugu:  [
    "9th Mile Corner",
    "Abor",
    "Achi",
    "Agbogugu",
    "Agbudu",
    "Akegbe Ugwu",
    "Akpugo",
    "Akwuke",
    "Amagunze",
    "Amechi",
    "Amechi Idodo",
    "Amodu",
    "Amokwe",
    "Amoli",
    "Amuri",
    "Aninri",
    "Awgu",
    "Eha-Amufu",
    "Eke",
    "Emene",
    "Ezeagu",
    "Ihe",
    "Isu Awaa",
    "Ituku",
    "Lejja",
    "Mgbowo",
    "Mpu",
    "Nara",
    "Nenwe",
    "Ngwo",
    "Nike",
    "Nkanu",
    "Nkerefi",
    "Nsukka",
    "Obe",
    "Oduma",
    "Ogbaku",
    "OgboduAba",
    "Oji River",
    "Okpanku",
    "Okpatu",
    "Opi",
    "Ozalla",
    "Udenu",
    "Udi",
    "Ugbawka",
    "Ugbo",
    "Ugwuaji",
    "Ugwuoba",
    "Umana",
    "Uzouwani",
    "Inyi",
  ]
};



